_BASE_: "Base-CustomText.yaml"
MODEL:
  WEIGHTS: "weights/batext/pretrain_attn_R_50.pth"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn" # "attn" "rnn"
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 1000
OUTPUT_DIR: "output/batext/customtext/attn_R_50"
